import { CaseStudy, ArchiveItem, SearchItem, FunResponse, ExperienceEntry } from '@/types';

export const CASE_STUDIES: CaseStudy[] = [
  {
    number: 'Casestudy 01',
    title: 'The Favric Expo',
    subtitle: 'Brand Identity & Exhibition',
    tasks: ['Brand Identity', 'Concept Development', 'Exhibition/Expo'],
    slug: 'the-favric-expo',
    baseImage: '/images/thefavricexpo/thefabricexpo-binder03-square.jpg',
    hoverImage: '/images/thefavricexpo/thefabricexpo-misc01-square.jpg',
  },
  {
    number: 'Casestudy 02',
    title: 'Gentle Dazs',
    subtitle: 'Brand Identity & Packaging',
    tasks: ['Brand Research', 'Concept Development', 'Brand Identity', 'Packaging'],
    slug: 'gentle-dazs',
    baseImage: '/images/gentledazs/GentleDazs_Packages_11.jpg',
    hoverImage: '/images/gentledazs/GentleDazs_Thumbnail.jpg',
  },
  {
    number: 'Casestudy 03',
    title: 'Lights of Seoul',
    subtitle: 'Brand Identity & Festival',
    tasks: ['Cultural Research', 'Concept Development', 'Visual Identity', 'Wayfinding'],
    slug: 'lights-of-seoul',
    baseImage: '/images/lightsofseoul/lightsofseoul_thumbnail_square.jpg',
    hoverImage: '/images/lightsofseoul/Digital_Ticket01-square.jpg',
  },
  {
    number: 'Casestudy 04',
    title: 'Trace Toronto',
    subtitle: 'Brand Identity & UX/UI (App)',
    tasks: ['UX Research & Strategy', 'Information Architecture', 'UI Design', 'Brand Identity'],
    slug: 'trace-toronto',
    baseImage: '/images/tracetoronto/tracetoronto-mac05-square.jpg',
    hoverImage: '/images/tracetoronto/tracetoronto-app02.jpg',
  },
  {
    number: 'Casestudy 05',
    title: "I Wasn't There",
    subtitle: 'Editorial',
    tasks: ['Concept Development', 'Literary Analysis', 'Editorial Design', 'Narrative Structuring'],
    slug: 'i-wasnt-there',
    baseImage: '/images/iwasntthere/iwasntthere_thumbnail.jpg',
    hoverImage: '/images/iwasntthere/iwasntthere_thumbnail-02.jpg',
  },
];

export const ARCHIVE_ITEMS: ArchiveItem[] = [
  {
    id: 'casestudy-item-5',
    title: 'Metallik Group LLC',
    category: 'Business Deck',
    year: '2026',
    date: '2026 January',
    tasks: ['Business Deal Presentation', 'Brand Stickers'],
    images: [
      '/images/metallik-group/metallik-group-thumbnail.jpg',
      '/images/metallik-group/metallik-group-content01.jpg',
      '/images/metallik-group/metallik-group-content03.jpg',
      '/images/metallik-group/metallik-group-content02.jpg',
    ],
  },
  {
    id: 'casestudy-item-6',
    title: 'Lazy Donut',
    category: 'Brand Identity & \nIllustration',
    year: '2025',
    date: '2025 April',
    tasks: ['Poster Design', 'Concept Development'],
    images: [
      '/images/lazydonut/lazydonut01.jpg',
      '/images/lazydonut/lazydonut02.jpg',
      '/images/lazydonut/lazydonut03.jpg',
      '/images/lazydonut/lazydonut04.jpg',
      '/images/lazydonut/lazydonut05.jpg',
    ],
    behanceUrl: 'https://www.behance.net/gallery/232735877/Lazy-Donut',
  },
  {
    id: 'casestudy-item-7',
    title: 'Brass Fork',
    category: 'Brand Identity &\nIllustration',
    year: '2025',
    date: '2025 December',
    tasks: ['Brand Identity', 'Illustration', 'Concept Development'],
    images: [
      '/images/brassfork/brassfork-brochure.jpg',
      '/images/brassfork/brassfork-brochure-detail.jpg',
      '/images/brassfork/brassfork-menu.jpg',
      '/images/brassfork/brassfork-totebag.jpg',
      '/images/brassfork/brassfork-food.jpg',
    ],
    behanceUrl: 'https://www.behance.net/gallery/232680255/Brass-Fork',
  },
  {
    id: 'casestudy-item-8',
    title: 'The Making of the Caribbean Landscape',
    category: 'Book Cover',
    year: '2025',
    date: '2025 December',
    tasks: ['Editorial', 'Book Cover Design'],
    images: [
      '/images/dalvorem/caribbean-book-01.jpg',
      '/images/dalvorem/caribbean-spine.jpg',
      '/images/dalvorem/caribbean-book-02.jpg',
    ],
    websiteUrl: 'https://dalvorem.com/publication',
  },
  {
    id: 'casestudy-item-9',
    title: 'Golden Africa Group',
    category: 'UX/UI (Dashboard)',
    year: '2025',
    date: '2025 November',
    tasks: ['UX Research & Strategy', 'UI Design'],
    images: [
      '/images/gag/gag-ui-login.jpg',
      '/images/gag/gag-ui-main.jpg',
      '/images/gag/gag-ui-investment.jpg',
      '/images/gag/gag-ui-contact.jpg',
    ],
    websiteUrl: 'https://pro-reactor.com/en/investment',
  },
  {
    id: 'casestudy-item-10',
    title: 'London Lyra School',
    category: 'Brand Identity',
    year: '2025',
    date: '2025 September',
    tasks: ['Brand Identity', 'Concept Development'],
    images: [
      '/images/london-school/london-school-logo.jpg',
      '/images/london-school/london-school-backpack.jpg',
      '/images/london-school/london-school-notebooks.jpg',
      '/images/london-school/london-school-wallsticker.jpg',
      '/images/london-school/london-school-certificate.jpg',
    ],
    websiteUrl: 'https://studiom416.com/3d-modeling-web-design-graphic-design-case-studies-gamedev-interior/',
  },
  {
    id: 'casestudy-item-11',
    title: 'Letterwaves',
    category: 'Data Visualization',
    year: '2025',
    date: '2025 January',
    tasks: ['Data Visualization', 'UX Research & Strategy', 'Information Architecture', 'UI Design'],
    images: ['/images/letterwaves/letterwaves-thumbnail.jpg'],
  },
  {
    id: 'casestudy-item-12',
    title: 'MetroArts Festival Committee',
    category: 'Brand Identity',
    year: '2025',
    date: '2025 August',
    tasks: ['Wayfinding', 'Icon Design', 'Information Design', 'System Design'],
    images: [
      '/images/metroarts/metroarts-poster-vinyl.jpg',
      '/images/metroarts/metroarts-logo.jpg',
      '/images/metroarts/metroarts-ticket.jpg',
      '/images/metroarts/metroarts-bc.jpg',
    ],
    behanceUrl: 'https://www.behance.net/gallery/232653985/MetroArts-Festival-Committee',
  },
  {
    id: 'casestudy-item-13',
    title: 'Do you see me?',
    category: 'Exhibition (Poster)',
    year: '2025',
    date: '2025 January',
    tasks: ['Poster Design', 'Concept Development'],
    images: [
      '/images/doyoublankme/doyoublankme-black.jpg',
      '/images/doyoublankme/doyoublankme-white.jpg',
    ],
  },
  {
    id: 'casestudy-item-18',
    title: 'Restaurant Operation',
    category: 'Data Visualization',
    year: '2025',
    date: '2025 December',
    tasks: ['UX Research & Strategy', 'Information Architecture', 'UI Design'],
    images: [
      '/images/restaurant-operation/restaurant-operation-illus.jpg',
      '/images/restaurant-operation/restaurant-operation-illus-scaled.jpg',
    ],
  },
  {
    id: 'casestudy-item-14',
    title: 'Herbert Bayer',
    category: 'Editorial (Magazine)',
    year: '2024',
    date: '2024 December',
    tasks: ['Concept Development', 'Literary Analysis', 'Editorial Design'],
    images: [
      '/images/herbertbayer/herbertbayer-01.jpg',
      '/images/herbertbayer/herbertbayer-02.jpg',
      '/images/herbertbayer/herbertbayer-03.jpg',
      '/images/herbertbayer/herbertbayer-04.jpg',
    ],
  },
];

export const SEARCH_ITEMS: SearchItem[] = [
  { label: 'Home', keywords: ['home'], url: '/' },
  { label: 'About', keywords: ['about', 'about me'], url: '/about' },
  { label: 'Contact', keywords: ['contact', 'co', 'con'], url: '/contact' },
  { label: 'Desire Art Museum', keywords: ['desire', 'art', 'museum', 'branding'], url: '/' },
  { label: 'The Favric Expo', keywords: ['favric', 'the favric', 'the', 'expo'], url: '/the-favric-expo' },
  { label: 'Gentle Dazs', keywords: ['gentle dazs', 'branding', 'packaging'], url: '/gentle-dazs' },
  { label: 'Trace Toronto', keywords: ['trace', 'toronto', 'ux', 'app'], url: '/trace-toronto' },
  { label: 'Lights of Seoul', keywords: ['lights', 'seoul', 'festival'], url: '/lights-of-seoul' },
  { label: "I Wasn't There", keywords: ["i wasn't there", 'book', 'typography'], url: '/i-wasnt-there' },
];

export const FUN_RESPONSES: FunResponse[] = [
  { triggers: ['hello', 'hi', 'hey'], message: ['Hi there 👋 Search anything!'] },
  { triggers: ['howdy'], message: ['Howdy 🤠'] },
  { triggers: ['good morning', 'morning'], message: ['Good morning ☀️'] },
  { triggers: ['good afternoon', 'afternoon', 'lunch'], message: ['Good afternoon. Time flies!'] },
  { triggers: ['good evening', 'evening', 'night', 'dinner', 'good night'], message: ['Late night browsing? 🌙'] },
  { triggers: ['sleep', 'go to bed'], message: ['Go to bed too! 😴'] },
  { triggers: ['sydney', 'sajal', 'sajal kanwal', 'kanwal'], message: ["Yes, Sajal is here. He's busy coding 💻"] },
  { triggers: ['who made this'], message: ['Guess who! 😎'] },
  { triggers: ['who are you'], message: ["I'm Sajal's search assistant! 😎"] },
  { triggers: ['are you human'], message: ['Depends on how you define human 🤔'] },
  { triggers: ['what are you hiding'], message: ['Shh… nothing 🤫'] },
  { triggers: ['secret'], message: ["Tell me yours first, then I'll tell you 😏"] },
  { triggers: ['what do you do', 'job'], message: ["I'm a search assistant 💃"] },
  { triggers: ['cool', 'nice', 'awesome', 'amazing', 'fabulous', 'sick'], message: ['You think so? Thanks!'] },
  { triggers: ['wow', 'whoa', 'woah', 'ooo'], message: ['I take it as a compliment!'] },
  { triggers: ['meow', 'miaow', 'purr', 'cat', 'kitty'], message: ['Purrrr 🐈‍⬛🐾'] },
  { triggers: ['bark', 'dog', 'puppy', 'woof'], message: ['Woof Woof 🐕 🐾'] },
  { triggers: ['shit'], message: ['🫢😧'] },
  { triggers: ['pretty', 'beautiful'], message: ['Thank you 🫶'] },
  { triggers: ['bestie', 'friend', 'friends'], message: ['🫵🤝'] },
  { triggers: ['coffee', 'expresso'], message: ['Go tell Sajal your favourite coffee shop ☕️'] },
  { triggers: ['starbucks'], message: ['Yes, my favourite ☕✨'] },
  { triggers: ['tim hortons', 'tims'], message: ['Iced capp with croissant for all seasons 🥐'] },
  { triggers: ['happy new year', 'new year', '2026'], message: ['Happy New Year! 🎉'] },
  { triggers: ['2025'], message: ['Hope your 2025 was amazing! 💫'] },
  { triggers: ['merry christmas', 'christmas'], message: ['Merry Christmas! 🎄🎅'] },
  { triggers: ['portfolio', 'website'], message: ["You're already here! Enjoy!"] },
  { triggers: ['project', 'work', 'casestudy', 'case study'], message: ["Sajal's favourites are Repo Lens & Sentinel ✨"] },
  { triggers: ['help'], message: ['Try searching for home, about, or project names (e.g. Repo Lens).'] },
  { triggers: ['yes'], message: ['😏'] },
  { triggers: ['no'], message: ['😏'] },
  { triggers: ['okay'], message: ['👌'] },
  { triggers: ['what'], message: ['Need help?'] },
  { triggers: ['you'], message: ['Yes, you 🫵'] },
  { triggers: ['?'], message: ['Fingers crossed 🤞'] },
  { triggers: ['!'], message: ['‼️🫢'] },
  { triggers: ['.'], message: ['Yes, period.'] },
  { triggers: ['email'], message: ['Contact me via sajal.kanwal02@gmail.com!'] },
  { triggers: ['linkedin', 'li'], message: ['Find me @sajal-kanwal in LinkedIn!'] },
  { triggers: ['instagram', 'ins'], message: ['Find me @sajal-kanwal in GitHub!'] },
];

export const EXPERIENCES: ExperienceEntry[] = [
  {
    title: 'Top 50 - Hack the Future',
    type: 'Hackathon',
    dates: '2025 Apr',
    company: 'GeeksforGeeks',
    location: 'Remote',
    logoSrc: '/images/profile/man.png',
  },
  {
    title: 'B.Tech CSE (DS & ML)',
    type: 'Student',
    dates: '2023 Aug–Present',
    company: 'Lovely Professional University',
    location: 'Phagwara, Punjab',
    logoSrc: '/images/profile/man.png',
  },
];

export const SOCIAL_LINKS = {
  linkedin: 'https://linkedin.com/in/sajal-kanwal',
  behance: 'https://github.com/Sajal-kanwal',
  instagram: 'https://github.com/Sajal-kanwal',
  github: 'https://github.com/Sajal-kanwal',
  email: 'mailto:sajal.kanwal02@gmail.com',
  calendly: 'mailto:sajal.kanwal02@gmail.com',
};
